dist:
  focal
sudo:
  require
language:
  cpp
compiler:
  clang
script:
  ./wasabi.sh
  source ./scripts/set_env.sh
  cmake -S. -Bbuild/linux/Debug -GNinja -DWASABI_ROOT_DIR=${TRAVIS_BUILD_DIR} -DWASMTIME=${TRAVIS_BUILD_DIR}/external/wasmtime/wasmtime -DSYSROOT_WASI_DIR=${TRAVIS_BUILD_DIR}/external/sysroot/wasi-sysroot -DSYSROOT_LINUX_DIR=${TRAVIS_BUILD_DIR}/external/sysroot/linux-sysroot -DLLVM_DIR=${TRAVIS_BUILD_DIR}/external/clang+llvm-11.0.0-x86_64-linux-gnu-ubuntu-20.04 -DCMAKE_MAKE_PROGRAM=${TRAVIS_BUILD_DIR}/external/ninja/ninja -DCMAKE_INSTALL_PREFIX:PATH=${TRAVIS_BUILD_DIR}/install/linux/Debug/ -DWASABI_PLATFORM_TARGET=linux -DCMAKE_BUILD_TYPE=Debug
  cmake --build build/linux/Debug --target install
  cd build/linux/Debug && ctest
