#pragma once

const char* createFashionTablesSQL =	
"CREATE TABLE Agg_yr_qt_mt_mn_wk_rg_cy_sn_sr_qt_ma (agg1_id INT NOT NULL, Yr NVARCHAR (4), Qtr NVARCHAR (2), Mth INT, Month_name NVARCHAR (10), Wk INT, City NVARCHAR (20), Store_name NVARCHAR (50), Sales_revenue NUMERIC, Quantity_sold INT, Margin NUMERIC (10, 2));\n"
"CREATE TABLE Agg_yr_qt_rn_st_ln_ca_sr (agg2_id INT NOT NULL, Yr NVARCHAR (4), Qtr NVARCHAR (2), State NVARCHAR (15), Line NVARCHAR (30), Category NVARCHAR (30), Sales_revenue NUMERIC (10, 2));\n"
"CREATE TABLE Article_Color_Lookup (Article_color_lookup_id INT, Article_id INT, Color_code INT, Article_label VARCHAR (255), Color_label VARCHAR (255), Category VARCHAR (255), Sale_price NUMERIC, Family_name VARCHAR (30), Family_code VARCHAR (3));\n"
"CREATE TABLE Article_lookup (Article_id INT, Article_label NVARCHAR (100), Category NVARCHAR (30), Sale_price NUMERIC (10, 2), Family_name NVARCHAR (30), Family_code NVARCHAR (3));\n"
"CREATE TABLE Article_Lookup_Criteria (\n"
"    Article_lookup_criteria_id INT            NOT NULL,\n"
"    Article_id                 INT,\n"
"    Criteria                   NVARCHAR (5),\n"
"    Criteria_type              NVARCHAR (5),\n"
"    Criteria_type_label        NVARCHAR (50),\n"
"    Criteria_label             NVARCHAR (100) \n"
");\n"
"CREATE TABLE Calendar_year_lookup (\n"
"    Week_id       INT,\n"
"    Week_In_Year  INT,\n"
"    Yr            NVARCHAR (4),\n"
"    Fiscal_Period NVARCHAR (4),\n"
"    Year_Week     NVARCHAR (7),\n"
"    Qtr           NVARCHAR (1),\n"
"    Month_Name    NVARCHAR (15),\n"
"    Mth           INT,\n"
"    Holiday_Flag  NVARCHAR (1) \n"
");\n"
"CREATE TABLE Outlet_Lookup (Shop_id INT, Shop_name NVARCHAR (50), Address_1 NVARCHAR (255), Manager NVARCHAR (255), Date_open NVARCHAR (255), Long_opening_hours_flag NVARCHAR (1), Owned_outright_flag NVARCHAR (1), Floor_space INT, Zip_code INT, City NVARCHAR (255), State NVARCHAR (255), City_Long DOUBLE, City_Lat DOUBLE);\n"
"CREATE TABLE product_promotion_facts (Product_promotion_facts_id INT NOT NULL, Article_id INT, Week_id INT, Promotion_id INT, Duration TINYINT, Promotion_cost DOUBLE);\n"
"CREATE TABLE promotion_lookup (\n"
"    Promotion_id     INT,\n"
"    Promotion_flag   NVARCHAR (1),\n"
"    Print_flag       NVARCHAR (1),\n"
"    Radio_flag       NVARCHAR (1),\n"
"    Television_flag  NVARCHAR (1),\n"
"    Direct_mail_flag NVARCHAR (1) \n"
");\n"
"CREATE TABLE Shop_facts (Shop_facts_id INT, Article_id INT, Color_code INT, Week_id INT, Shop_id INT, Margin NUMERIC, Amount_sold NUMERIC, Quantity_sold INT, Invoice_DateTime DATETIME, Invoice_Date DATE);\n"
" \n"
"-- INDEX\n"
"CREATE INDEX \"Article_Code\" on \"Article_Lookup_Criteria\" (\n"
"   \"Article_id\" ASC\n"
");\n"
"CREATE INDEX Article_id ON Article_Color_Lookup (\"Article_id\" ASC);\n"
"CREATE INDEX Article_lookup_article_id ON Article_lookup (\"Article_id\" ASC);\n"
"CREATE INDEX Article_lookupproduct_promotio ON product_promotion_facts (\"Article_id\" ASC);\n"
"CREATE INDEX Calendar_year_lookupproduct_pr ON product_promotion_facts (\"Week_id\" ASC);\n"
"CREATE INDEX Code_Magasin ON Outlet_Lookup (\"Shop_id\" ASC);\n"
"CREATE INDEX Code_Pays ON Outlet_Lookup (\"State\" ASC);\n"
"CREATE INDEX Code_Postal ON Outlet_Lookup (\"Zip_code\" ASC);\n"
"CREATE INDEX Family_Code ON Article_lookup (\"Family_code\" ASC);\n"
"CREATE UNIQUE INDEX PrimaryKey ON product_promotion_facts (\"Product_promotion_facts_id\" ASC);\n"
"CREATE INDEX Shop_factsArticle_id ON Shop_facts (\"Article_id\" ASC);\n"
"CREATE INDEX Shop_factsShop_id ON Shop_facts (\"Shop_id\" ASC);\n"
"CREATE INDEX Shop_facts_id ON Shop_facts (\"Shop_facts_id\" ASC);\n"
"CREATE INDEX Shop_id ON Outlet_Lookup (\"Shop_id\" ASC);\n"
"CREATE INDEX Shop_name ON Outlet_Lookup (\"Shop_name\" ASC);\n"
"CREATE INDEX Start_week ON product_promotion_facts (\"Week_id\" ASC);\n"
"CREATE INDEX Ville ON Outlet_Lookup (\"City\" ASC);\n"
"CREATE INDEX \"Week_id\" on \"Calendar_year_lookup\" (\n"
"   \"Week_id\" ASC\n"
");\n"
"CREATE UNIQUE INDEX agg1_id ON Agg_yr_qt_mt_mn_wk_rg_cy_sn_sr_qt_ma (\"agg1_id\" ASC);\n"
"CREATE UNIQUE INDEX agg2_id ON Agg_yr_qt_rn_st_ln_ca_sr (\"agg2_id\" ASC);\n"
"CREATE INDEX id ON product_promotion_facts (\"Product_promotion_facts_id\" ASC);\n"
"CREATE INDEX product_key ON product_promotion_facts (\"Article_id\" ASC);\n"
"CREATE INDEX promotion_key ON product_promotion_facts (\"Promotion_id\" ASC);\n"
"CREATE INDEX promotion_lookupproduct_promot ON product_promotion_facts (\"Promotion_id\" ASC);\n"
;