#pragma once

const char* data_Article_lookup = 
"INSERT INTO Article_lookup VALUES(\"115121\",\"Pastel Colored Viscose Scarf\",\"Hats,gloves,scarves\",\"90\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"116256\",\"Flower Patterned Viscose Scarf\",\"Hats,gloves,scarves\",\"62.1\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"119427\",\"Stole and Feather Boa Set\",\"Jewelry\",\"110\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"120114\",\"Leather Belt\",\"Belts,bags,wallets\",\"79.9\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"121764\",\"Bell Necklace\",\"Jewelry\",\"69.9\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"122709\",\"Pendant Earrings\",\"Jewelry\",\"69.99\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"128390\",\"Suede Lyris Skirt\",\"Mini city\",\"163.9\",\"City Skirts\",\"F16\");\n"
"INSERT INTO Article_lookup VALUES(\"128969\",\"Multicolored T-Shirt\",\"T-Shirts\",\"82.8\",\"Sweat-T-Shirts\",\"F36\");\n"
"INSERT INTO Article_lookup VALUES(\"129925\",\"Rigid Droplet Necklace\",\"Jewelry\",\"224.1\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"136786\",\"Rigid Twisted Knot Bracelet\",\"Jewelry\",\"83.5\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"137635\",\"Tartan Long-Sleeved Turtleneck\",\"Turtleneck\",\"99.99\",\"Sweaters\",\"F25\");\n"
"INSERT INTO Article_lookup VALUES(\"137638\",\"Shell Headband\",\"Hair accessories\",\"161.99\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"137838\",\"Sketched Flowers Silk Scarf\",\"Hats,gloves,scarves\",\"34.3\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"138627\",\"Belt Buckle\",\"Belts,bags,wallets\",\"109.5\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"139111\",\"Pearl and Flower Necklace\",\"Jewelry\",\"129.99\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"139590\",\"1m Feather Boa\",\"Hats,gloves,scarves\",\"87.1\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"140515\",\"9cm Gold Brooch\",\"Jewelry\",\"99\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"141012\",\"Ball and Chain Necklace\",\"Jewelry\",\"79.2\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"141401\",\"Rose Patterned Brushed Silk Scarf\",\"Hats,gloves,scarves\",\"79.2\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"141406\",\"Belted Tunic\",\"Lounge wear\",\"105\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"141683\",\"Long Stemmed Rose Patterned Viscose Scarf\",\"Hats,gloves,scarves\",\"154.8\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"142500\",\"Chain and Pearl Necklace\",\"Jewelry\",\"69.3\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"142905\",\"Long Trousers\",\"Long lounge pants\",\"34.3\",\"City Trousers\",\"F2\");\n"
"INSERT INTO Article_lookup VALUES(\"143269\",\"Jacquard Scarf\",\"Hats,gloves,scarves\",\"105\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"143847\",\"Large Silver Bracelet\",\"Jewelry\",\"69.3\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"143848\",\"Patchwork Leather Belt\",\"Belts,bags,wallets\",\"88.9\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"143903\",\"Buttoned Jumper Dress\",\"Casual dresses\",\"116.1\",\"Dresses\",\"F80\");\n"
"INSERT INTO Article_lookup VALUES(\"143994\",\"Patchwork Flower Patterned Viscose Scarf\",\"Hats,gloves,scarves\",\"99\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"143995\",\"Leaf and Flower Patterned Viscose Scarf\",\"Hats,gloves,scarves\",\"99\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"144100\",\"Rose Patterned Viscose Scarf\",\"Hats,gloves,scarves\",\"99\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"144102\",\"Rounded Gold Brooch\",\"Jewelry\",\"220.1\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"144251\",\"Geometric Patterned Viscose Scarf\",\"Hats,gloves,scarves\",\"50\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"144289\",\"Snake Loop Necklace\",\"Jewelry\",\"150\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"144290\",\"Rose Leaf Patterned  Viscose Scarf\",\"Hats,gloves,scarves\",\"149.99\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"144912\",\"Black Pearl Necklace\",\"Jewelry\",\"215.2\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"144921\",\"Diamond Bracelet\",\"Jewelry\",\"169\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"144928\",\"Jet and Pearl Necklace\",\"Jewelry\",\"135.2\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"144940\",\"Herringbone Cardigan\",\"Cardigan\",\"169.5\",\"Sweaters\",\"F25\");\n"
"INSERT INTO Article_lookup VALUES(\"144944\",\"Flower Patterned T-Shirt\",\"T-Shirts\",\"142\",\"Sweat-T-Shirts\",\"F36\");\n"
"INSERT INTO Article_lookup VALUES(\"144945\",\"Scattered Flower Patterned Viscose Scarf\",\"Hats,gloves,scarves\",\"155\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"145403\",\"Grooved Nickel Bracelet\",\"Jewelry\",\"155\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"145404\",\"Rounded Rectangle Brooch\",\"Jewelry\",\"238.8\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"146334\",\"Large Rose Patterned Viscose Scarf\",\"Hats,gloves,scarves\",\"139.3\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"146378\",\"Tulip Patterned Viscose Scarf\",\"Hats,gloves,scarves\",\"114.73\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"146379\",\"Milkyway Pocket Shirt\",\"2 Pocket shirts\",\"159.2\",\"Shirt Waist\",\"F20\");\n"
"INSERT INTO Article_lookup VALUES(\"146552\",\"Crocodile Wallet\",\"Belts,bags,wallets\",\"129.67\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"146751\",\"Pearl and Diamond Necklace\",\"Jewelry\",\"142.73\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"147070\",\"Pearl Droplet Necklace\",\"Jewelry\",\"199\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"147915\",\"Rosebud Patterned Viscose Scarf\",\"Hats,gloves,scarves\",\"110\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"148002\",\"Large Rectangular Brooch\",\"Jewelry\",\"116.1\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"148032\",\"Sandrine Stole\",\"Hair accessories\",\"145\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"148353\",\"Leather Gloves\",\"Hats,gloves,scarves\",\"89.54\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"148540\",\"Small Pearl Droplet Necklace\",\"Jewelry\",\"159.2\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"148622\",\"Aaron Sweater\",\"Soft fabric\",\"127.65\",\"Sweaters\",\"F25\");\n"
"INSERT INTO Article_lookup VALUES(\"149110\",\"Thick Silver Bangle\",\"Jewelry\",\"129\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"149121\",\"Sunflower Patterned Viscose Scarf\",\"Hats,gloves,scarves\",\"134.1\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"150850\",\"Zipper Vest\",\"Lounge wear\",\"69\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"151807\",\"Velvet Purse\",\"Belts,bags,wallets\",\"116.1\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"151810\",\"Goldset Pearl Necklace\",\"Jewelry\",\"134.1\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"155570\",\"Diamond Pendant Earrings\",\"Jewelry\",\"118.5\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"155576\",\"Rudolph Shirt\",\"Lounge wear\",\"110.6\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"155716\",\"Patchwork Velvet Scarf\",\"Hats,gloves,scarves\",\"118.5\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"155939\",\"E-Watch\",\"Jewelry\",\"110.6\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"156171\",\"Lyrics Shorts\",\"Party pants\",\"118.5\",\"Trousers\",\"F3\");\n"
"INSERT INTO Article_lookup VALUES(\"156173\",\"Jet Pearl Bracelet\",\"Jewelry\",\"118.5\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"157518\",\"Velvet Jacket\",\"Fancy fabric\",\"118.5\",\"Jackets\",\"F45\");\n"
"INSERT INTO Article_lookup VALUES(\"157599\",\"Flower Stem Patterned Silk Scarf\",\"Hats,gloves,scarves\",\"118.5\",\"Outerwear\",\"F50\");\n"
"INSERT INTO Article_lookup VALUES(\"158152\",\"Blazer\",\"Day wear\",\"114.55\",\"Outerwear\",\"F50\");\n"
"INSERT INTO Article_lookup VALUES(\"159172\",\"Mini Pearl and Tubes Necklace\",\"Jewelry\",\"118.5\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"159421\",\"Striped Leggings\",\"Lounge wear\",\"210.6\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"159438\",\"Double Ball and Chain Necklace\",\"Jewelry\",\"218.5\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"159454\",\"Tie-die Patterned Viscose Scarf\",\"Hats,gloves,scarves\",\"118.5\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"159705\",\"Jet Pearl Choker\",\"Jewelry\",\"155\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"159769\",\"Strawberry Patterned Viscose Scarf\",\"Hats,gloves,scarves\",\"118.5\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"159907\",\"Tortoiseshell Brooch\",\"Jewelry\",\"135\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"159908\",\"Polka dot Viscose Scarf\",\"Hats,gloves,scarves\",\"110.6\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"160209\",\"Cloud Patterned Viscose Scarf\",\"Hats,gloves,scarves\",\"110.6\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"160243\",\"Suede Cloth Belt\",\"Belts,bags,wallets\",\"118.5\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"160370\",\"Pearl Pendant  Necklace\",\"Jewelry\",\"176.5\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"160371\",\"Rigid Ball Necklace\",\"Jewelry\",\"176.5\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"160556\",\"Spotty Leggings\",\"Lounge wear\",\"110.6\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"160812\",\"Multicolored Pearl Necklace\",\"Jewelry\",\"189.9\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"161363\",\"Double Breasted Silk Jacket\",\"Lounge wear\",\"180\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"162520\",\"Diamond Star Earrings\",\"Jewelry\",\"201.9\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"162541\",\"Suede Belt with Heart Shaped Buckle\",\"Belts,bags,wallets\",\"211\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"162542\",\"Two Color Double Sided Velvet Scarf\",\"Hats,gloves,scarves\",\"111\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"162655\",\"Sleeveless Jumper Dress\",\"Casual dresses\",\"140\",\"Dresses\",\"F80\");\n"
"INSERT INTO Article_lookup VALUES(\"162674\",\"Corduroy Jacket\",\"Outdoor\",\"160\",\"Jackets\",\"F45\");\n"
"INSERT INTO Article_lookup VALUES(\"162840\",\"Aladdin Silk Trousers\",\"Party pants\",\"110.6\",\"Trousers\",\"F3\");\n"
"INSERT INTO Article_lookup VALUES(\"163019\",\"Shetland Jacket\",\"Day wear\",\"190\",\"Outerwear\",\"F50\");\n"
"INSERT INTO Article_lookup VALUES(\"163490\",\"Bengal Striped Medium Trousers\",\"Jeans\",\"118.5\",\"Trousers\",\"F3\");\n"
"INSERT INTO Article_lookup VALUES(\"163506\",\"Square Neck Jumper Dress\",\"Casual dresses\",\"118.5\",\"Dresses\",\"F80\");\n"
"INSERT INTO Article_lookup VALUES(\"163584\",\"Business Travel Bag\",\"Belts,bags,wallets\",\"151\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"163907\",\"Burlington Jacket\",\"Outdoor\",\"158\",\"Jackets\",\"F45\");\n"
"INSERT INTO Article_lookup VALUES(\"164356\",\"Velvet Leotard T-Shirt\",\"T-Shirts\",\"184.5\",\"Sweat-T-Shirts\",\"F36\");\n"
"INSERT INTO Article_lookup VALUES(\"164962\",\"Belted Pocket Shirt\",\"Short sleeve\",\"259.5\",\"Shirt Waist\",\"F20\");\n"
"INSERT INTO Article_lookup VALUES(\"165170\",\"Modal Shirt\",\"Short sleeve\",\"259.5\",\"Shirt Waist\",\"F20\");\n"
"INSERT INTO Article_lookup VALUES(\"165197\",\"Cotton Leotard T-Shirt\",\"Short sleeve\",\"118.5\",\"Shirt Waist\",\"F20\");\n"
"INSERT INTO Article_lookup VALUES(\"166136\",\"Chenille Leotard T-Shirt\",\"Short sleeve\",\"118.5\",\"Shirt Waist\",\"F20\");\n"
"INSERT INTO Article_lookup VALUES(\"166544\",\"Polo Collared T-Shirt\",\"T-Shirts\",\"255.5\",\"Sweat-T-Shirts\",\"F36\");\n"
"INSERT INTO Article_lookup VALUES(\"166550\",\"Whisky Dancer T-Shirt\",\"Short sleeve\",\"255.5\",\"Shirt Waist\",\"F20\");\n"
"INSERT INTO Article_lookup VALUES(\"166553\",\"Long-Sleeved Torn Stitch T-Shirt\",\"Long sleeve\",\"255.5\",\"Shirt Waist\",\"F20\");\n"
"INSERT INTO Article_lookup VALUES(\"166579\",\"Stretch Jeans\",\"Jeans\",\"210\",\"Trousers\",\"F3\");\n"
"INSERT INTO Article_lookup VALUES(\"166583\",\"Military Shirt\",\"2 Pocket shirts\",\"190\",\"Shirt Waist\",\"F20\");\n"
"INSERT INTO Article_lookup VALUES(\"166699\",\"Suede Stretch Dress\",\"Evening wear\",\"145\",\"Dresses\",\"F80\");\n"
"INSERT INTO Article_lookup VALUES(\"167017\",\"Crewneck Stitch Tunic\",\"Sweater dresses\",\"236.6\",\"Dresses\",\"F80\");\n"
"INSERT INTO Article_lookup VALUES(\"167042\",\"Long-Sleeved Stitch Shirt\",\"Long sleeve\",\"193.5\",\"Shirt Waist\",\"F20\");\n"
"INSERT INTO Article_lookup VALUES(\"167106\",\"Thinsulate Knit Gloves\",\"Hats,gloves,scarves\",\"237\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"167119\",\"Jacquard T-Shirt\",\"Lounge wear\",\"150\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"167681\",\"Canvas Jacket\",\"Outdoor\",\"225\",\"Jackets\",\"F45\");\n"
"INSERT INTO Article_lookup VALUES(\"167695\",\"Pomodore Lace T-Shirt\",\"T-Shirts\",\"222\",\"Sweat-T-Shirts\",\"F36\");\n"
"INSERT INTO Article_lookup VALUES(\"167727\",\"High Collar Engineers Raincoat\",\"Wet wear\",\"290\",\"Overcoats\",\"F90\");\n"
"INSERT INTO Article_lookup VALUES(\"167731\",\"Zipper Sweat Shirt\",\"Sweats\",\"200\",\"Sweat-T-Shirts\",\"F36\");\n"
"INSERT INTO Article_lookup VALUES(\"167809\",\"Long-sleeved Crewneck T-Shirt\",\"T-Shirts\",\"220\",\"Sweat-T-Shirts\",\"F36\");\n"
"INSERT INTO Article_lookup VALUES(\"167846\",\"Side Slit Long Skirt\",\"Full length\",\"348.6\",\"City Skirts\",\"F16\");\n"
"INSERT INTO Article_lookup VALUES(\"168230\",\"Lyrics Trousers\",\"Long lounge pants\",\"348.6\",\"City Trousers\",\"F2\");\n"
"INSERT INTO Article_lookup VALUES(\"168499\",\"Twill Dressing-gown\",\"Night wear\",\"403.5\",\"Outerwear\",\"F50\");\n"
"INSERT INTO Article_lookup VALUES(\"168852\",\"Silver Hoop Earrings\",\"Jewelry\",\"118.5\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"168963\",\"Herringbone Sweater\",\"Turtleneck\",\"348.6\",\"Sweaters\",\"F25\");\n"
"INSERT INTO Article_lookup VALUES(\"168994\",\"Velour Overcoat\",\"Dry wear\",\"403.5\",\"Overcoats\",\"F90\");\n"
"INSERT INTO Article_lookup VALUES(\"169011\",\"Fake Fur Overcoat\",\"Dry wear\",\"348.6\",\"Overcoats\",\"F90\");\n"
"INSERT INTO Article_lookup VALUES(\"169227\",\"Leather Trousers\",\"Pants\",\"348.6\",\"Leather\",\"F65\");\n"
"INSERT INTO Article_lookup VALUES(\"169253\",\"Alaska Satin Belt\",\"Belts,bags,wallets\",\"298.5\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"169254\",\"Chenille Astro Hat\",\"Hats,gloves,scarves\",\"320.6\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"169272\",\"Hair Clip\",\"Hair accessories\",\"118.5\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"169301\",\"Printed Lyrics Trousers\",\"Party pants\",\"298.5\",\"Trousers\",\"F3\");\n"
"INSERT INTO Article_lookup VALUES(\"169306\",\"Long-Sleeved Velvet T-Shirt\",\"T-Shirts\",\"236.6\",\"Sweat-T-Shirts\",\"F36\");\n"
"INSERT INTO Article_lookup VALUES(\"169432\",\"Trenchcoat\",\"Wet wear\",\"320.6\",\"Overcoats\",\"F90\");\n"
"INSERT INTO Article_lookup VALUES(\"169476\",\"Stretch Cotton Raincoat\",\"Wet wear\",\"320.6\",\"Overcoats\",\"F90\");\n"
"INSERT INTO Article_lookup VALUES(\"169478\",\"Round Comb\",\"Hair accessories\",\"205\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"169571\",\"Canvas Shorts\",\"Bermudas\",\"278.6\",\"City Trousers\",\"F2\");\n"
"INSERT INTO Article_lookup VALUES(\"169776\",\"Navy Blue Greatcoat\",\"Jackets\",\"278.6\",\"Leather\",\"F65\");\n"
"INSERT INTO Article_lookup VALUES(\"170016\",\"Johnny Walker Turtleneck Loop Sweater\",\"Turtleneck\",\"418.6\",\"Sweaters\",\"F25\");\n"
"INSERT INTO Article_lookup VALUES(\"170108\",\"Loose-Fitting Turtleshell\",\"Sweats\",\"297.7\",\"Sweat-T-Shirts\",\"F36\");\n"
"INSERT INTO Article_lookup VALUES(\"170875\",\"Orange Short-sleeved Shirt\",\"Short sleeve\",\"180.6\",\"Shirt Waist\",\"F20\");\n"
"INSERT INTO Article_lookup VALUES(\"170928\",\"Short Jumper Dress\",\"Casual dresses\",\"376.6\",\"Dresses\",\"F80\");\n"
"INSERT INTO Article_lookup VALUES(\"171284\",\"Burlington Trousers\",\"Long lounge pants\",\"323.7\",\"City Trousers\",\"F2\");\n"
"INSERT INTO Article_lookup VALUES(\"171407\",\"Corduroy Shorts\",\"Bermudas\",\"323.7\",\"City Trousers\",\"F2\");\n"
"INSERT INTO Article_lookup VALUES(\"171889\",\"Crew Necked Cashmere Sweater\",\"Soft fabric\",\"278.6\",\"Sweaters\",\"F25\");\n"
"INSERT INTO Article_lookup VALUES(\"171910\",\"Violon T-Shirt\",\"T-Shirts\",\"229\",\"Sweat-T-Shirts\",\"F36\");\n"
"INSERT INTO Article_lookup VALUES(\"172438\",\"Cable Stitch Knitted Jacket\",\"Boatwear\",\"208.6\",\"Jackets\",\"F45\");\n"
"INSERT INTO Article_lookup VALUES(\"172909\",\"Polar Collar Jacket\",\"Fancy fabric\",\"208.6\",\"Jackets\",\"F45\");\n"
"INSERT INTO Article_lookup VALUES(\"173115\",\"Printed Apple Tree Skirt\",\"Full length\",\"323.7\",\"City Skirts\",\"F16\");\n"
"INSERT INTO Article_lookup VALUES(\"173117\",\"Diamond Patterned Vest\",\"Short sleeve\",\"323.7\",\"Shirt Waist\",\"F20\");\n"
"INSERT INTO Article_lookup VALUES(\"173404\",\"Milanese Tunic\",\"Shirts\",\"323.7\",\"Leather\",\"F65\");\n"
"INSERT INTO Article_lookup VALUES(\"173608\",\"Tailored Short-sleeved Shirt\",\"Short sleeve\",\"120.99\",\"Shirt Waist\",\"F20\");\n"
"INSERT INTO Article_lookup VALUES(\"173658\",\"Sleeveless Plunge Neckline Dress\",\"Evening wear\",\"265\",\"Dresses\",\"F80\");\n"
"INSERT INTO Article_lookup VALUES(\"173673\",\"Astro Tank Top\",\"Soft fabric\",\"185\",\"Sweaters\",\"F25\");\n"
"INSERT INTO Article_lookup VALUES(\"173941\",\"Clown Printed Satin Trousers\",\"Party pants\",\"185\",\"Trousers\",\"F3\");\n"
"INSERT INTO Article_lookup VALUES(\"173974\",\"Milanese Pocket Shirt\",\"Short sleeve\",\"185\",\"Shirt Waist\",\"F20\");\n"
"INSERT INTO Article_lookup VALUES(\"177231\",\"Romane Long-Sleeved Shirt\",\"Long sleeve\",\"165\",\"Shirt Waist\",\"F20\");\n"
"INSERT INTO Article_lookup VALUES(\"177232\",\"Poplin Pocket Shirt\",\"2 Pocket shirts\",\"202\",\"Shirt Waist\",\"F20\");\n"
"INSERT INTO Article_lookup VALUES(\"177248\",\"Viscose Stretch Shirt\",\"Long sleeve\",\"149\",\"Shirt Waist\",\"F20\");\n"
"INSERT INTO Article_lookup VALUES(\"177264\",\"Long-Sleeved Crewneck T-Shirt\",\"T-Shirts\",\"188\",\"Sweat-T-Shirts\",\"F36\");\n"
"INSERT INTO Article_lookup VALUES(\"177271\",\"Check Turtle Neck Sweater\",\"Turtleneck\",\"297.7\",\"Sweaters\",\"F25\");\n"
"INSERT INTO Article_lookup VALUES(\"177275\",\"Loose-Fitting T-Shirt\",\"T-Shirts\",\"169\",\"Sweat-T-Shirts\",\"F36\");\n"
"INSERT INTO Article_lookup VALUES(\"177325\",\"Chenille Sweater\",\"Soft fabric\",\"215\",\"Sweaters\",\"F25\");\n"
"INSERT INTO Article_lookup VALUES(\"177368\",\"Stretch Denim Shirt\",\"Long sleeve\",\"191\",\"Shirt Waist\",\"F20\");\n"
"INSERT INTO Article_lookup VALUES(\"177376\",\"Sequin Dress\",\"Evening wear\",\"172\",\"Dresses\",\"F80\");\n"
"INSERT INTO Article_lookup VALUES(\"177380\",\"Milanese Stitch Shirt\",\"2 Pocket shirts\",\"199\",\"Shirt Waist\",\"F20\");\n"
"INSERT INTO Article_lookup VALUES(\"177497\",\"Straight Belted Skirt\",\"Skirts\",\"185\",\"Dresses\",\"F80\");\n"
"INSERT INTO Article_lookup VALUES(\"177798\",\"Polo Zipper Jacket\",\"Boatwear\",\"180\",\"Jackets\",\"F45\");\n"
"INSERT INTO Article_lookup VALUES(\"177860\",\"Sports Bag\",\"Belts,bags,wallets\",\"199\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"177875\",\"Silk Sequined Shirt\",\"Short sleeve\",\"165\",\"Shirt Waist\",\"F20\");\n"
"INSERT INTO Article_lookup VALUES(\"178435\",\"Velvet Shoulder Bag\",\"Belts,bags,wallets\",\"208.6\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"178628\",\"Lyrics Herringbone Sweater\",\"Soft fabric\",\"210\",\"Sweaters\",\"F25\");\n"
"INSERT INTO Article_lookup VALUES(\"178769\",\"Long-sleeved Missoni T-Shirt\",\"T-Shirts\",\"235\",\"Sweat-T-Shirts\",\"F36\");\n"
"INSERT INTO Article_lookup VALUES(\"178788\",\"Operette Striped Sweater\",\"Soft fabric\",\"130\",\"Sweaters\",\"F25\");\n"
"INSERT INTO Article_lookup VALUES(\"178835\",\"Pencil Skirt\",\"Skirts\",\"153\",\"Dresses\",\"F80\");\n"
"INSERT INTO Article_lookup VALUES(\"178903\",\"Cowl Neck Tunic\",\"Sweater dresses\",\"196\",\"Dresses\",\"F80\");\n"
"INSERT INTO Article_lookup VALUES(\"179075\",\"Cotton Print Skirt\",\"Skirts\",\"198\",\"Dresses\",\"F80\");\n"
"INSERT INTO Article_lookup VALUES(\"179169\",\"Multicolored Sweater\",\"Soft fabric\",\"188\",\"Sweaters\",\"F25\");\n"
"INSERT INTO Article_lookup VALUES(\"179204\",\"Cheyenne Poloshirt\",\"T-Shirts\",\"185\",\"Sweat-T-Shirts\",\"F36\");\n"
"INSERT INTO Article_lookup VALUES(\"179739\",\"Crepe Stitch Shirt\",\"Sweats\",\"150\",\"Sweat-T-Shirts\",\"F36\");\n"
"INSERT INTO Article_lookup VALUES(\"179740\",\"Pleated Skirt\",\"Skirts\",\"162.5\",\"Dresses\",\"F80\");\n"
"INSERT INTO Article_lookup VALUES(\"180030\",\"Multicolored Striped T-Shirt\",\"T-Shirts\",\"225\",\"Sweat-T-Shirts\",\"F36\");\n"
"INSERT INTO Article_lookup VALUES(\"180368\",\"Jacquard Turtleneck\",\"T-Shirts\",\"178\",\"Sweat-T-Shirts\",\"F36\");\n"
"INSERT INTO Article_lookup VALUES(\"180372\",\"Orangina Lace Shirt\",\"T-Shirts\",\"155\",\"Sweat-T-Shirts\",\"F36\");\n"
"INSERT INTO Article_lookup VALUES(\"181009\",\"Panache Belted Dress\",\"Skirts\",\"207\",\"Dresses\",\"F80\");\n"
"INSERT INTO Article_lookup VALUES(\"181248\",\"Hooded Velvet Sweatshirt\",\"Sweats\",\"211\",\"Sweat-T-Shirts\",\"F36\");\n"
"INSERT INTO Article_lookup VALUES(\"181252\",\"Crepe Trousers\",\"Party pants\",\"212\",\"Trousers\",\"F3\");\n"
"INSERT INTO Article_lookup VALUES(\"181756\",\"Striped Turtleneck\",\"Turtleneck\",\"149\",\"Sweaters\",\"F25\");\n"
"INSERT INTO Article_lookup VALUES(\"182313\",\"Square Viscose Sample\",\"Samples\",\"120\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"182330\",\"Tapestry Turtleneck Sweater\",\"Turtleneck\",\"152.5\",\"Sweaters\",\"F25\");\n"
"INSERT INTO Article_lookup VALUES(\"182331\",\"Tartan Dress\",\"Casual dresses\",\"150\",\"Dresses\",\"F80\");\n"
"INSERT INTO Article_lookup VALUES(\"182343\",\"Fabric Sampler\",\"Samples\",\"134.33\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"182379\",\"Lyrics Leotard\",\"Lounge wear\",\"129\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"182488\",\"Chenille Leotard T-Shirt\",\"Lounge wear\",\"180\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"182880\",\"Diamond Cigarette Holder\",\"Lounge wear\",\"167\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"182919\",\"Long Lace Skirt\",\"Full length\",\"139\",\"City Skirts\",\"F16\");\n"
"INSERT INTO Article_lookup VALUES(\"183572\",\"Crushed Velvet Sweatshirt\",\"Sweats\",\"204\",\"Sweat-T-Shirts\",\"F36\");\n"
"INSERT INTO Article_lookup VALUES(\"183592\",\"Quilted Lyrics Skirt\",\"Mini city\",\"210\",\"City Skirts\",\"F16\");\n"
"INSERT INTO Article_lookup VALUES(\"183720\",\"V Stitch Tunic\",\"Sweater dresses\",\"145\",\"Dresses\",\"F80\");\n"
"INSERT INTO Article_lookup VALUES(\"183801\",\"Missoni Stitch Shirt\",\"Sweats\",\"174\",\"Sweat-T-Shirts\",\"F36\");\n"
"INSERT INTO Article_lookup VALUES(\"183836\",\"Smoking Jacket\",\"Fancy fabric\",\"202\",\"Jackets\",\"F45\");\n"
"INSERT INTO Article_lookup VALUES(\"183861\",\"Lyrics Culotte Shorts\",\"Lounge wear\",\"155\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"183869\",\"Vivaldi Cotton Sweatshirt\",\"Sweats\",\"145\",\"Sweat-T-Shirts\",\"F36\");\n"
"INSERT INTO Article_lookup VALUES(\"184215\",\"Goat Wool Skirt\",\"Mini city\",\"185\",\"City Skirts\",\"F16\");\n"
"INSERT INTO Article_lookup VALUES(\"184264\",\"Grenelle Printed Jeans\",\"Jeans\",\"192\",\"Trousers\",\"F3\");\n"
"INSERT INTO Article_lookup VALUES(\"184352\",\"Modigliani Zipper Sweatshirt\",\"Sweats\",\"184\",\"Sweat-T-Shirts\",\"F36\");\n"
"INSERT INTO Article_lookup VALUES(\"184561\",\"Multicolored Chenille Sweater\",\"Soft fabric\",\"146\",\"Sweaters\",\"F25\");\n"
"INSERT INTO Article_lookup VALUES(\"185114\",\"2 Row Pearl Necklace\",\"Jewelry\",\"161\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"185125\",\"Wool and Lyrics Trousers\",\"Long lounge pants\",\"182\",\"City Trousers\",\"F2\");\n"
"INSERT INTO Article_lookup VALUES(\"185203\",\"Burlington Canvas Jacket\",\"Boatwear\",\"136\",\"Jackets\",\"F45\");\n"
"INSERT INTO Article_lookup VALUES(\"185403\",\"Starlet Jacket\",\"Fancy fabric\",\"161\",\"Jackets\",\"F45\");\n"
"INSERT INTO Article_lookup VALUES(\"186108\",\"Vivaldi Tunic\",\"Long sleeve\",\"159\",\"Shirt Waist\",\"F20\");\n"
"INSERT INTO Article_lookup VALUES(\"186370\",\"Flounced Collar Shirtdress\",\"Long sleeve\",\"200\",\"Shirt Waist\",\"F20\");\n"
"INSERT INTO Article_lookup VALUES(\"187710\",\"Africa Zipper Cardigan\",\"Cardigan\",\"231\",\"Sweaters\",\"F25\");\n"
"INSERT INTO Article_lookup VALUES(\"187901\",\"Fake Leopard Skin Gloves with Lyrics Trim\",\"Hats,gloves,scarves\",\"852.5\",\"Accessories\",\"F60\");\n"
"INSERT INTO Article_lookup VALUES(\"187904\",\"Denim Front Button Dress\",\"Casual dresses\",\"127.5\",\"Dresses\",\"F80\");\n"
"INSERT INTO Article_lookup VALUES(\"189479\",\"Whisky Dancer T-Shirt\",\"T-Shirts\",\"214\",\"Sweat-T-Shirts\",\"F36\");\n"
;